### ISSUE TITLE
Segfault on install

### ISSUE THREAD

**Issue by pbarker** [sl1pm4t/k2tf#100]
Installed using the homebrew package, now any commands segfault:

```
> k2tf -f cluster-role-binding.yaml
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff207f4c9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff207f4c9e
stack: frame={sp:0x7ffeefbff288, fp:0x7ffeefbff2d8} stack=[0x7ffeefb80328,0x7ffeefbff390)
0x00007ffeefbff188:  0x01007ffeefbff1a8  0x0000000000000004
0x00007ffeefbff198:  0x000000000000001f  0x00007fff207f4c9e
0x00007ffeefbff1a8:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff1b8:  0x0000000004036971 <runtime.throw+0x0000000000000071>  0x00007ffeefbff258
0x00007ffeefbff1c8:  0x0000000005c9ae0a  0x00007ffeefbff210
0x00007ffeefbff1d8:  0x0000000004036c28 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000071674a0
0x00007ffeefbff1e8:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff1f8:  0x00007ffeefbff258  0x0000000004036971 <runtime.throw+0x0000000000000071>
0x00007ffeefbff208:  0x00000000071674a0  0x00007ffeefbff248
0x00007ffeefbff218:  0x0000000004036bb0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff228
0x00007ffeefbff228:  0x0000000004036be0 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000071674a0
0x00007ffeefbff238:  0x0000000004036971 <runtime.throw+0x0000000000000071>  0x00007ffeefbff258
0x00007ffeefbff248:  0x00007ffeefbff278  0x0000000004036971 <runtime.throw+0x0000000000000071>
0x00007ffeefbff258:  0x00007ffeefbff260  0x00000000040369a0 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff268:  0x0000000005cbaf76  0x000000000000002a
0x00007ffeefbff278:  0x00007ffeefbff2c8  0x000000000404c3d6 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff288: <0x0000000005cbaf76  0x0000000006eb3ff8
0x00007ffeefbff298:  0x00007ffeefbff308  0x0000000004029766 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff2a8:  0x000000c0001cb538  0x0000000004011ddb <runtime.mapassign+0x000000000000011b>
0x00007ffeefbff2b8:  0x000000c0000001a0  0x0000000000000000
0x00007ffeefbff2c8:  0x00007ffeefbff310 !0x00007fff207f4c9e
0x00007ffeefbff2d8: >0x00007ffeefbff310  0x000000000703c000
0x00007ffeefbff2e8:  0x000000000000048e  0x0000000004e810e5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff2f8:  0x0000000004069a1f <runtime.syscall+0x000000000000001f>  0x000000c0001cb710
0x00007ffeefbff308:  0x0000000007167d00  0x000000c0001cb6e0
0x00007ffeefbff318:  0x0000000004067870 <runtime.asmcgocall+0x0000000000000070>  0x00007ffeefbff350
0x00007ffeefbff328:  0x0000000004010aae <runtime.persistentalloc.func1+0x000000000000002e>  0x0000000000001018
0x00007ffeefbff338:  0x00007ffeefbff350  0x000000000719e4d8
0x00007ffeefbff348:  0x0000000000000948  0x000000c0000001a0
0x00007ffeefbff358:  0x0000000004065989 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff368:  0x0000000005fd3bc0  0x00000000071674a0
0x00007ffeefbff378:  0x00007ffeefbff3c8  0x0000000004065885 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff388:  0x000000000406583d <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x5cbaf76, 0x6eb3ff8})
	runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff207f4c9e
stack: frame={sp:0x7ffeefbff288, fp:0x7ffeefbff2d8} stack=[0x7ffeefb80328,0x7ffeefbff390)
0x00007ffeefbff188:  0x01007ffeefbff1a8  0x0000000000000004
0x00007ffeefbff198:  0x000000000000001f  0x00007fff207f4c9e
0x00007ffeefbff1a8:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff1b8:  0x0000000004036971 <runtime.throw+0x0000000000000071>  0x00007ffeefbff258
0x00007ffeefbff1c8:  0x0000000005c9ae0a  0x00007ffeefbff210
0x00007ffeefbff1d8:  0x0000000004036c28 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000071674a0
0x00007ffeefbff1e8:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff1f8:  0x00007ffeefbff258  0x0000000004036971 <runtime.throw+0x0000000000000071>
0x00007ffeefbff208:  0x00000000071674a0  0x00007ffeefbff248
0x00007ffeefbff218:  0x0000000004036bb0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff228
0x00007ffeefbff228:  0x0000000004036be0 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000071674a0
0x00007ffeefbff238:  0x0000000004036971 <runtime.throw+0x0000000000000071>  0x00007ffeefbff258
0x00007ffeefbff248:  0x00007ffeefbff278  0x0000000004036971 <runtime.throw+0x0000000000000071>
0x00007ffeefbff258:  0x00007ffeefbff260  0x00000000040369a0 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff268:  0x0000000005cbaf76  0x000000000000002a
0x00007ffeefbff278:  0x00007ffeefbff2c8  0x000000000404c3d6 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff288: <0x0000000005cbaf76  0x0000000006eb3ff8
0x00007ffeefbff298:  0x00007ffeefbff308  0x0000000004029766 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff2a8:  0x000000c0001cb538  0x0000000004011ddb <runtime.mapassign+0x000000000000011b>
0x00007ffeefbff2b8:  0x000000c0000001a0  0x0000000000000000
0x00007ffeefbff2c8:  0x00007ffeefbff310 !0x00007fff207f4c9e
0x00007ffeefbff2d8: >0x00007ffeefbff310  0x000000000703c000
0x00007ffeefbff2e8:  0x000000000000048e  0x0000000004e810e5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff2f8:  0x0000000004069a1f <runtime.syscall+0x000000000000001f>  0x000000c0001cb710
0x00007ffeefbff308:  0x0000000007167d00  0x000000c0001cb6e0
0x00007ffeefbff318:  0x0000000004067870 <runtime.asmcgocall+0x0000000000000070>  0x00007ffeefbff350
0x00007ffeefbff328:  0x0000000004010aae <runtime.persistentalloc.func1+0x000000000000002e>  0x0000000000001018
0x00007ffeefbff338:  0x00007ffeefbff350  0x000000000719e4d8
0x00007ffeefbff348:  0x0000000000000948  0x000000c0000001a0
0x00007ffeefbff358:  0x0000000004065989 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff368:  0x0000000005fd3bc0  0x00000000071674a0
0x00007ffeefbff378:  0x00007ffeefbff3c8  0x0000000004065885 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff388:  0x000000000406583d <runtime.rt0_go+0x000000000000013d>
runtime.sigpanic()
	runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x4e810e0, 0x1, 0x40487413, 0xc0001cb7a0)
	runtime/sys_darwin.go:22 +0x3b fp=0xc0001cb710 sp=0xc0001cb6f0 pc=0x406427b
syscall.syscall(0x40b7a26, 0xc000138020, 0xc0001cb7c8, 0x40b7958)
	<autogenerated>:1 +0x26 fp=0xc0001cb758 sp=0xc0001cb710 pc=0x406a1e6
golang.org/x/sys/unix.ioctl(0x5c69713, 0x4, 0x100000449d23c)
	golang.org/x/sys@v0.0.0-20210502180810-71e4cd670f79/unix/zsyscall_darwin_amd64.go:690 +0x39 fp=0xc0001cb788 sp=0xc0001cb758 pc=0x4e80c39
golang.org/x/sys/unix.IoctlGetTermios(...)
	golang.org/x/sys@v0.0.0-20210502180810-71e4cd670f79/unix/ioctl.go:73
github.com/mattn/go-isatty.IsTerminal(0x5c69713)
	github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:10 +0x50 fp=0xc0001cb7f8 sp=0xc0001cb788 pc=0x50fd0b0
github.com/fatih/color.init()
	github.com/fatih/color@v1.10.0/color.go:21 +0x7a fp=0xc0001cb830 sp=0xc0001cb7f8 pc=0x50ff0da
runtime.doInit(0x704a3a0)
	runtime/proc.go:6498 +0x123 fp=0xc0001cb968 sp=0xc0001cb830 pc=0x40462e3
runtime.doInit(0x7056360)
	runtime/proc.go:6475 +0x71 fp=0xc0001cbaa0 sp=0xc0001cb968 pc=0x4046231
runtime.doInit(0x705a400)
	runtime/proc.go:6475 +0x71 fp=0xc0001cbbd8 sp=0xc0001cbaa0 pc=0x4046231
runtime.doInit(0x7061080)
	runtime/proc.go:6475 +0x71 fp=0xc0001cbd10 sp=0xc0001cbbd8 pc=0x4046231
runtime.doInit(0x704eac0)
	runtime/proc.go:6475 +0x71 fp=0xc0001cbe48 sp=0xc0001cbd10 pc=0x4046231
runtime.doInit(0x70592e0)
	runtime/proc.go:6475 +0x71 fp=0xc0001cbf80 sp=0xc0001cbe48 pc=0x4046231
runtime.main()
	runtime/proc.go:238 +0x1e6 fp=0xc0001cbfe0 sp=0xc0001cbf80 pc=0x4039286
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc0001cbfe8 sp=0xc0001cbfe0 pc=0x4067b61

goroutine 35 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x6a
created by k8s.io/klog/v2.init.0
	k8s.io/klog/v2@v2.8.0/klog.go:418 +0xfb
```

This is on macOS Big Sur 11.6.2

**Comment by pbarker** [comment]
Everything works find if I directly download and install the latest tag

**Comment by sl1pm4t** [comment]
Closing. Same issue as #90
